import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import { DevtoolsProvider } from "@providers/devtools";
import { RefineProvider } from "./RefineProvider";  // 👈 thêm dòng này
import "@refinedev/antd/dist/reset.css";

export const metadata: Metadata = {
  title: "Quản lý sản phẩm",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineProvider defaultMode={defaultMode}>
            {children}
          </RefineProvider>
        </Suspense>
      </body>
    </html>
  );
}
